[versions]
commonsMath3 = "3.6.1"
firebaseDatabase = "20.3.1"
google-material = "1.11.0"
googleServices = "4.4.1"
kakao = "3.5.1"
mockitoCore = "3.12.4"
navigationVersion = "2.7.7"
retrofit2Version = "2.9.0"
okhttp3Version = "4.9.1"
coroutinesVersion = "1.7.3"
lifecycleVersion = "2.7.0"
fragmentVersion = "1.6.2"
gsonVersion = "2.8.9"
koin_version = "3.5.0"
core-ktx = "1.13.0"
appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"
junit = "4.13.2"
junit-ext = "1.1.5"
espresso-core = "3.5.1"
org-jetbrains-kotlin-android = "1.9.0"
agp = "8.1.2"
legacy-support-v4 = "1.0.0"

[libraries]
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commonsMath3" }
core-ktx-1_9_0 = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabase" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
kakao = { module = "io.github.kakaocup:kakao", version.ref = "kakao" }
material-1_11_0 = { module = "com.google.android.material:material", version.ref = "google-material" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
navigation-fragment-ktx = {group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationVersion"}
navigation-ui-ktx = {group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationVersion"}
retrofit2 = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2Version"}
retrofit2-converter-gson = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2Version"}
okhttp3 = {group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3Version"}
okhttp3-logging-interceptor = {group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3Version"}
kotlinx-coroutines-core = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesVersion"}
kotlinx-coroutines-android = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesVersion"}
lifecycle-viewmodel-ktx = {group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion"}
lifecycle-livedata-ktx = {group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleVersion"}
fragment-ktx = {group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentVersion"}
gson = {group = "com.google.code.gson", name = "gson", version.ref = "gsonVersion"}
koin-core = {group = "io.insert-koin", name = "koin-core", version.ref = "koin_version"}
koin-android = {group = "io.insert-koin", name = "koin-android", version.ref = "koin_version"}
koin-test = {group = "io.insert-koin", name = "koin-test", version.ref = "koin_version"}
core-ktx = {group = "androidx.core", name = "core-ktx", version.ref = "core-ktx"}
appcompat = {group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat"}
material = {group = "com.google.android.material", name = "material", version.ref = "material"}
constraintlayout = {group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout"}
junit = {group = "junit", name = "junit", version.ref = "junit"}
junit-ext = {group = "androidx.test.ext", name = "junit", version.ref = "junit-ext"}
espresso-test = {group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core"}
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy-support-v4" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version = "22.3.1" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version = "20.4.3" }
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx", version = "20.3.1" }
junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version = "1.1.5" }

[bundles]
navigation = ["navigation-fragment-ktx", "navigation-ui-ktx"]
retrofit2 = ["retrofit2", "retrofit2-converter-gson"]
okhttp3 = ["okhttp3", "okhttp3-logging-interceptor"]
coroutines = ["kotlinx-coroutines-android", "kotlinx-coroutines-core"]
lifecycle = ["lifecycle-livedata-ktx", "lifecycle-viewmodel-ktx"]
koin = ["koin-android", "koin-core", "koin-test"]
firebase = ["firebase-database", "firebase-auth-ktx", "firebase-common-ktx", "firebase-database-ktx"]

[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
com-android-library = { id = "com.android.library", version.ref = "agp" }